lab9: main.c list.c files.c
	gcc -std=c99 -o lab9 main.c list.c files.c 
	./lab9 data.txt test.bin

lab10: main1.c list1.c files1.c
	gcc -std=c99 -lpthread -o lab10 main1.c list1.c files1.c
	./lab10 data.txt test.bin autosave.txt
